# Generated by Django 2.2.5 on 2019-09-25 13:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField('Realtor', 'phone', models.CharField(max_length=20)),
        migrations.AlterField('Realtor', 'email', models.CharField(max_length=20))
    ]
